### ISSUE TITLE
Including APKs in Repo

### ISSUE THREAD

**Issue by Shadow53** [lineageos4microg/android_prebuilts_prebuiltapks#10]
The OpenGapps people had repositories containing prebuilt apks [taken down](https://opengapps.org/blog/post/2019/02/17/github-situation/) from GitHub. This project should probably consider alternative ways of hosting/obtaining the apks in case GitHub decides to crack down harder on this.

It looks like most, if not all of the binary files in this repository can be downloaded from other locations, so maybe the Android.mk files can be updated to download the files from official locations instead?

**Comment by Iolaum** [comment]
I believe that situation was resolved. Here's their [blog post about it](https://opengapps.org/blog/post/2019/02/17/github-situation/?back=true) and [here are some instructions on how to include opengapps in custom builds](https://github.com/opengapps/aosp_build#getting-started).

**Comment by spolack** [comment]
Lets work on it once it gets a real issue.
