### ISSUE TITLE
Enable call recordig in Dialer.apk

### ISSUE THREAD

**Issue by zabbal** [lineageos4microg/android_prebuilts_prebuiltapks#12]
The Dialer from LOS enable/disable call recording based on MCC/MNC which is braindead from the legal standpoint: if you travel with German SIM to Italy it doesn't mean that you bring with you magic bubble of German laws on call recording floating around your SIM card - you're governed by the laws of the country you're in. Hence the sane way to do this is to let user check that it's legal (out of band) and enable/disable it manually (disabled by default) regardless of MCC/MNC.

Would be nice to get this implemented right in L4M.

I've read that http://resurrectionremix.com/ have this enabled by default as well.

**Comment by spolack** [comment]
We base our work on a vanilla lineageos. That wont change. If you need some custom changes, consider building yourself.
