### ISSUE TITLE
Missing permissions for GmsCore causes bootloop

### ISSUE THREAD

**Issue by dp-alvarez** [lineageos4microg/android_prebuilts_prebuiltapks#13]
Currently fresh installs of LineageOS for microG causes bootloops on devices. The problem apparently is the "android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST" permission is missing on "privapp-permissions-com.google.android.gms.xml"

More information, and credits to, cha0sh3r0 on https://forum.xda-developers.com/showpost.php?p=79726273&postcount=1417

**Comment by dp-alvarez** [comment]
@corna Tagging you as I'm not sure this issue board is being monitored

**Comment by corna** [comment]
Done in b2c3b23, thanks
Let me know if it fixes the issues.
