### ISSUE TITLE
Update microG

### ISSUE THREAD

**Issue by ale5000-git** [lineageos4microg/android_prebuilts_prebuiltapks#18]
@johannesneyer
@corna

The current release is broken for many things.
mar-v-in have released a nightly build for the mapbox version with post-release fixes: https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk

Could you please include it?

**Comment by corna** [comment]
Sure, I'll do it soon

**Comment by ale5000-git** [comment]
Thanks.
Also there is another thing:

The mapbox version support
```
arm64-v8a
armeabi-v7a
x86
x86_64
```

Instead the vtm version support
```
arm64-v8a
armeabi
armeabi-v7a
x86
x86_64
```

So, for plain armeabi devices (without armeabi-v7a support) you need to use the vtm version instead.
The mapbox apk will still works on plain armeabi devices but it will crash when the maps api v2 are used.

The vtm version with post-release fixes is here: https://microg.org/dl/GmsCore-v0.2.8.17785-2-8a0010a-vtm.apk

**Comment by Miaourt** [comment]
Up, v0.2.10.19420 is out :)

**Comment by spolack** [comment]
Outdated.
