### ISSUE TITLE
Apps not drawing map

### ISSUE THREAD

**Issue by Shifty86** [lineageos4microg/android_prebuilts_prebuiltapks#2]
I am having a problem with apps not drawing maps, they however are able to got a location and draw indicators, the maps themselves are just blank. 

I have a fresh install of the Hammerhead zip, I have given UnifiedNlp all the required rights, self-check indicated everything is ok and backends are enabled.  

On the microg issues page I have been unable to find any similar problems so I am guessing it is somehow related to lineageos4microg

**Comment by corna** [comment]
This problem seems related to the Maps API, not with UnifiedNLP (Maps API are responsible for the drawing of the maps, UnifiedNLP is responsible just for the geolocalization). I doubt however that this problem is related to lineageos4microg, we ship the unmodified APKs from microG.

**Comment by Lanchon** [comment]
wrong project, abandoned, please close.
