### ISSUE TITLE
Update Weather Provider to Lineage 16

### ISSUE THREAD

**Issue by danielk43** [lineageos4microg/android_prebuilts_prebuiltapks#21]
Now that the default branch for the [docker image](https://github.com/lineageos4microg/docker-lineage-cicd) is updated, the current v14 weather provider seems like it should be also.

Thank you for all the great work on these projects.

**Comment by Iey4iej3** [comment]
I would like to suggest the removal of weather providers. The goal of LOS for microG is to make microG work painlessly. The weather provider seems unimportant and increases tasks of maintenance. There are several weather widgets on F-Droid, on the other hand.

**Comment by spolack** [comment]
I have removed them.
