### ISSUE TITLE
[Suggestion] Switch from Yalp Store to Aurora Store

### ISSUE THREAD

**Issue by braniii** [lineageos4microg/android_prebuilts_prebuiltapks#23]
The yalp store with anonymous login is rarely working. Normally I need to try at least a dozen different accounts, before I am able to download an app. Hence, I would suggest to switch to the [aurora store](https://gitlab.com/AuroraOSS/AuroraStore) which offers starting from v3 [aurora services](https://gitlab.com/AuroraOSS/AuroraServices). The app is well-maintained and offers a more reliable performance than yalp store.

**Comment by spolack** [comment]
I agree.

**Comment by ghost** [comment]
I think the sole purpose of this project should be to include those MicroG APKs that need signature spoofing.
All other modifications should be up to the LineageOS developers.
Keep it simple.

**Comment by famo** [comment]
I don't see yalp onmy installation here. This issue can probably be closed...

**Comment by braniii** [comment]
Currently, I have switched to a different OS, it seems to be fixed
