### ISSUE TITLE
river (moto g7)  sleep = death

### ISSUE THREAD

**Issue by ForestJohnson** [lineageos4microg/android_prebuilts_prebuiltapks#24]
Hello  lineageos4microg  

I am noob!! I don't know where to submit this issue, but I figured somewhere is better than nowhere.

I have a Moto G7 Power and I tried installing both

lineageOS for MicroG (https://download.lineage.microg.org/river/lineage-16.0-20191128-microG-river.zip)

and 

Stock lineageOS 16 (https://mirrorbits.lineageos.org/full/river/20191203/lineage-16.0-20191203-nightly-river-signed.zip)

When I booted into lineageOS for MicroG I very quickly realized this was not going to work for me.  As soon as the device went to sleep (or, something called "doze" in logcat, it seemed), it would never wake up again. pressing the power button did nothing, no logs were printed, it just sat there silently mocking me.  The issue could be re-produced by either letting the device sit for a minute and fall asleep, or by pressing the power button to lock the screen.

The only way to get out of it was to hold the power button and reboot the phone. 

I was looking around in logcat and I saw a lot of stuff, but nothing I recognized (I am not an android developer person!) Also this is really embarrassing but I never saved the log output properly. I am looking around at what I did save and its not really good enough for a  bug report. 

Anways then I used TWRP to format the phones storage again and re-install lineageOS from lineageOS website, not from lineageos for microG. This time it did not have the bug. the phone does not freeze after sleeping. 

To be honest I am a lazy pleb user and I don't really want to be bothered to dig too much into this.  I do like the idea of your project though so if you really wanna dig into this and you don't have your own Moto G7 device to test with (or if you cannot reproduce)  then I can wipe me phone again and do the following test to re-produce:

1. follow the official lineageOS river installations instructions and sideload lineageos4microg
2. boot the phone and go through the 1st run process to get to the home screen
3. turn on developer options and turn on ADB, connect to adb and make sure you can logcat.
4. unplug the phone from the computer (I was most reliably able to reproduce this when the phone was not connected via USB)  and  let the phone sit until sleep or press power button
5. at this point the phone should be still running in sleepy mode and power button does nothing. no wake up, no screen back light turning on. 
6. reconnect and logcat everything that happened since the last logcat

________________

re-do steps 1-6 but this time with the stock lineageOS.  The bug should not be present and in theory the difference between the two logcat outputs should point to the issue in question.

The most scary thing I remember seeing in the logcat output when the bug was present (logcat output that my  stupid ass didnt save!!!!!!!!!!)  was a `WATCHDOG KILLING SYSTEM PROCESS` message similar to  https://forum.xda-developers.com/showpost.php?p=74125072&postcount=8717

**Comment by fearlessiron** [comment]
@ForestJohnson Did you try it again with a later build, e.g. [this one](https://download.lineage.microg.org/river/lineage-16.0-20191212-microG-river.zip)? The death after sleep bug was a kernel problem (i.e. it had nothing to do with microG) and that bug has been fixed upstream lately. Giving it another shot might be worth it.

**Comment by ForestJohnson** [comment]
Thank you for the info! Once I have some time for this I will definitely try again.

**Comment by spolack** [comment]
Unrelated to microG.
