### ISSUE TITLE
AuroraServices

### ISSUE THREAD

**Issue by 532910** [lineageos4microg/android_prebuilts_prebuiltapks#25]
Please include AuroraServices as a system app the same way it's done for F-Droid Privileged Extension: https://gitlab.com/AuroraOSS/AuroraServices

**Comment by ghormoon** [comment]
hi, i'm looking here now and then and there's still no reply. is it just because of lack of time or is there some reason why devs don't want to include this?
would a PR speed it up? :)

**Comment by corna** [comment]
Lack of time and, according to the dev, [it's still not ready yet](https://gitlab.com/AuroraOSS/AuroraServices/issues/2).
Once it's published in FDroid we will consider it.

**Comment by ghormoon** [comment]
i'd like to reopen the discussion here
aurora store itself is on fdroid and i'd say stable enough
the extension itself doesn't make sense on fdroid -> you need to install it as system app, same as fdroid extension
what would it need to fulfill so it can be accepted here?

**Comment by ghost** [comment]
I think the sole purpose of this project should be to include those MicroG APKs that need signature spoofing.
All other modifications should be up to the LineageOS developers.
Keep it simple.

**Comment by spolack** [comment]
I agree - AuroraStore performs well without the Services. Lets not bloat L4M.  Close.

**Comment by JuniorJPDJ** [comment]
> the extension itself doesn't make sense on fdroid -> you need to install it as system app, same as fdroid extension

You could just update it from F-Droid like you do with microG
