### ISSUE TITLE
Update gmsCore to 0.2.11

### ISSUE THREAD

**Issue by poshul** [lineageos4microg/android_prebuilts_prebuiltapks#30]
I started working on this in my PR, but it ended up being more complicated than I had initially expected. Just doing a drop in replacement of the new 2.11 apk results in the phone getting stuck in the boot animation (on Enchilada. ADB still worked.) I'm going to try to work on this with my limited time, but would really appreciate any help.

**Comment by spolack** [comment]
I'm trying to bring up new builds soon. Beforehand i'll provide testbuilds. 

Version is updated.

**Comment by poshul** [comment]
Cheers! This works for me with Enchilada. I'm hoping that we get another version update from the gmsCore team soon to include the infection tracking API.
