### ISSUE TITLE
gsmCore v0.2.13.203915 and new fakeStore are available

### ISSUE THREAD

**Issue by DPTJKKVH** [lineageos4microg/android_prebuilts_prebuiltapks#33]
The new gsmCore v0.2.13.203915 is available and should be added to the prebuilts:

https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.13.203915

Also FakeStore seems to have gotten an update: https://github.com/microg/FakeStore/releases/tag/v0.1.0

**Comment by bananer** [comment]
Here's a PR for GmsCore: https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/pull/34

FakeStore 0.1.0 ist still marked as "preview" in F-Droid, that's why I did not include it for now.

**Comment by DPTJKKVH** [comment]
Updates have been added by team. :+1:
