### ISSUE TITLE
Include IzzyOnDroid repo with additional_repos.xml?

### ISSUE THREAD

**Issue by IzzySoft** [lineageos4microg/android_prebuilts_prebuiltapks#35]
Not sure which ROMs are using this repo, but it might be useful to include [my repo](https://apt.izzysoft.de/fdroid) with `additional_repos.xml`. As this "stinks" a little like ego-promo :mask:, let me give some background:

* my repo currently holds close to 600 apps – usually those not (yet) fully compliant with F-Droid's includion policy, but pretty close to
* my repo is to F-Droid like something in between "nonfree" and "universe" to Debian
* apps in my repo are the originals from their resp. developers, signed with their keys (which is why F-Droid doesn't include it by default: I don't build the apps myself from their resp. sources)
* APKs are checked against various tools (currently: VirusTotal plus a local library scanner; identified libraries are listed on the website)
* no tracking apart from the usual web server logs, which are rotated to `/dev/null` after a couple of weeks and are only consulted for trouble-shooting (I'm a privacy proponent and known as such)
* and yes, I'm one of the F-Droid maintainers :wink: – but I'm not asking in that role (so this is no "official request from F-Droid", but rather my personal suggestion)

No bad feelings if you say "no", it's just a suggestion. After all you even include tools to access Google Play :rofl: So my suggestion is to include my repo but have it turned off by default, so users can easily enable it if they want to. There's no "archive", just the "main repo".

You might wish to do the same for the [Kali Nethunter repo](https://store.nethunter.com/repo/), btw, for another ~50 apps.

**Comment by ghost** [comment]
I think the sole purpose of this project should be to include those MicroG APKs that need signature spoofing.
All other modifications should be up to the LineageOS developers.
Keep it simple.

**Comment by famo** [comment]
I think it is a bad idea to add random repos by default in the installation, because this is a matter of trust.

If there is a toggle in the welcome dialog, by which user could enable additional repos (opt-in), than I'm all for it. But please not by default behind the users back.

**Comment by IzzySoft** [comment]
@famo that's exactly what I meant. Quote (with emphasis):

> include my repo but **_have it turned off by default,_** so users can easily enable it if they want to.

Full ack to this being a matter of trust – and my repo simply does not deserve that level of trust to come "enabled by default" – despite all the precautions I take to make it as safe as possible. I think it's pretty good, but the decision whether it's "good enough" should be left to the user. No bad feelings if someone doesn't feel it "good enough" (except if the same person thinks Play Store deserves the trust, as that I'd feel schizophrenic :wink:).

Btw, I think some other repos fall into the very same category (deserving to be pre-configured but off by default), like [Bromite](https://www.bromite.org/fdroid), [CalyxOS](https://calyxos.gitlab.io/calyx-fdroid-repo/fdroid/repo/index.xml), [Droidware](https://github.com/ungoogled-software/ungoogled-chromium-android) (ungoogled Chromium), [Firefox unofficial](https://forum.f-droid.org/t/separate-non-free-firefox-repo/944) (Firefox, Kiwi, Signal, Wire …).

> All other modifications should be up to the LineageOS developers.

Does "plain LineageOS" even include F-Droid by default? If not, that argument doesn't even fit the case.

> my repo currently holds close to 600 apps

Just 3 months later, and the number must be corrected: it's "close to 700" meanwhile (681 at the time of writing this) – raising the number of apps available to over 4k (4042 with F-Droid + microG + IoD; F-Droid itself currently has 3347 apps, so it's a plus of 20%).

**Comment by bananer** [comment]
While I appreciate the efforts of people running F-Droid repos, I don't think they should be added to the lineageos4microg ROM by default.

Including F-Droid with the microG repos makes sense to keep the included microG packages up to date.

Including other repos would be free advertisement or scope creep in the best case and a whole lot of new issues in the worst case. Just one example: CalyxOS contains a `com.android.webview` package, certainly with a different signature then the one included in official builds in this rom.

**Comment by spolack** [comment]
Thank you @bananer

**Comment by IzzySoft** [comment]
Thanks for considering at least. I understand the decision – though I hoped for a different outcome :wink:
