### ISSUE TITLE
ErrorCode::kDownloadMetadataSignatureMismatch when trying to sideload

### ISSUE THREAD

**Issue by xerz-one** [lineageos4microg/android_prebuilts_prebuiltapks#39]
Using LineageOS Recovery version 17.1 (20201225) on my Xperia XZ2 Compact, when trying to install LineageOS for microG I get the following error:

```
Error applying update: 26 (ErrorCode::kDownloadMetadataSignatureMismatch)
E:Error in /sideload/package.zip (status 1)
```

I found a few instances of people finding this issue, but no one actually solving it:

https://www.reddit.com/r/MicroG/comments/idgitj/signature_mismatch_on_microg_los17/
https://www.reddit.com/r/MicroG/comments/j2uyr1/how_to_install_lineageos_for_microg_on_a_pixel_3a/g80axat/
https://www.reddit.com/r/MicroG/comments/i2e5ki/fxtec_pro%C2%B9/
https://forum.xda-developers.com/t/help-how-to-install-lineageos-for-microg.4173783/

**Comment by xerz-one** [comment]
After further searching, this workaround did the trick for me! This isn't enough to close the ticket imho, but at the very least it gets the job done https://github.com/lineageos4microg/docker-lineage-cicd/issues/105#issuecomment-700635488

**Comment by FarisZR** [comment]
> After further searching, this workaround did the trick for me! This isn't enough to close the ticket imho, but at the very least it gets the job done [lineageos4microg/docker-lineage-cicd#105 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/105#issuecomment-700635488)

thank you, can confirm this workaround works on a pixel 4 XL
