### ISSUE TITLE
include unifiednlp too

### ISSUE THREAD

**Issue by pgera** [lineageos4microg/android_prebuilts_prebuiltapks#4]
I see that this repo doesn't include unifiednlp separately. It includes the other microg stuff, which acts like a superset, but from my understanding, it should be possible to use unifiednlp on its own in less intrusive ways. I would like to use this repo for some builds, and test the following options in increasing order of intrusiveness:

- unifiednlp as a network provider. Doesn't need signature spoofing (this is called gapps mode confusingly in the original repo). config_locationProviderPackageNames should have org.microg.nlp and the app should be a system app from my reading.  
- unifiednlp no gapps mode. This needs signature spoofing. This is still useful on its own without using full microg for getting navigation apps to work.
- entire microg. This is already done right now.

**Comment by corna** [comment]
Valid point, I'll add it.

I'm not sure about the second, I think it should work also without signature spoofing.

**Comment by pgera** [comment]
Based on my understanding, the second one corresponds to com.google.android.gms (https://f-droid.org/en/packages/com.google.android.gms/) whereas the first one corresponds to org.microg.nlp  (https://f-droid.org/en/packages/org.microg.nlp/). Hence, the 2nd one is the commonly used one which needs spoofing. There's also com.google.android.maps (the one in this repo) which corresponds to the legacy maps api I guess. So that's also a spoofing version. However, I don't see it included in the patch. Is it even used ?

**Comment by corna** [comment]
AFAIK the signature spoofing is needed to spoof microG's GmsCore as authentic for the Play Services client library included in the APKs.

On the other hand, the location services just check whether:
 * the location provider is a priv-app (Android >= 6.0)
 * the location provider's name is in [config_locationProviderPackageNames](https://github.com/LineageOS/android_frameworks_base/blob/lineage-15.1/core/res/res/values/config.xml#L1509)

From its point of view, com.google.android.gms is a name like another, nothing here should require the signature spoofing.

Also note that, if you just need UnifiedNlp and you're building your own ROM, the first one should be the best choice, as no signature spoofing is required, you're not using a Google package name and you're still able to install Gapps along UnifiedNlp (if needed).

**Comment by pgera** [comment]
I was thinking of taking a crack at it. What would be the required permissions in permissions xml file ? Based on your privapp-permissions-com.google.android.gms.xml, this would need android.permission.INSTALL_LOCATION_PROVIDER. However, based on the [f-droid package description](https://f-droid.org/en/packages/com.google.android.gms/), it also needs the following permissions: 
```
android.permission.INSTALL_LOCATION_PROVIDER
android.permission.ACCESS_COARSE_UPDATES
android.permission.ACCESS_COARSE_LOCATION
android.permission.RECEIVE_BOOT_COMPLETED
org.microg.permission.FORCE_COARSE_LOCATION
com.android.settings.INJECT_SETTINGS 
```
Do I need all of these ? Based on this [comment](https://github.com/microg/android_packages_apps_GmsCore/issues/366#issuecomment-427252345), it looks like ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION are needed, but the package itself doesn't mention ACCESS_FINE_LOCATION. Also not sure about the other permissions.

**Comment by ghost** [comment]
I think the sole purpose of this project should be to include those MicroG APKs that need signature spoofing.
All other modifications should be up to the LineageOS developers.
Keep it simple.

**Comment by bananer** [comment]
This repo only serves the lineageos4microg builds. If you want to include any other app for your own builds, feel free to fork.
