### ISSUE TITLE
What is the Goal of this Fork?

### ISSUE THREAD

**Issue by famo** [lineageos4microg/android_prebuilts_prebuiltapks#42]
Hello,
I was wondering if there is a statement somewhere what actually is the goal of this fork or if someone could give me an clarification here.

Obviously it is to provide microG out-of-the-box and then there is also F-Droid included. But in addition to that? Any plans to [de-google](https://www.reddit.com/r/privacy/comments/cldrym/how_to_degoogle_lineageos_in_2019/), add more privacy or usability features to this fork?

Ty

**Comment by bananer** [comment]
Did the website https://lineage.microg.org/ not answer that question for you?

**Comment by famo** [comment]
No.

**Comment by doodhout** [comment]
I don't think there's any plans beyond prepackaging MicroG and F-Droid inside a standard LineageOS image.

But that doesn't stop anyone else from doing what you asked for, of course. That's the beauty of it all: some people can choose the vanilla builds from here. Others can choose the sprinkled ones like the one you propose, if anyone were ever to provide those.

**Comment by spolack** [comment]
> But that doesn't stop anyone else from doing what you asked for, of course. That's the beauty of it all: some people can choose the vanilla builds from here. Others can choose the sprinkled ones like the one you propose, if anyone were ever to provide those.

indeed!
