### ISSUE TITLE
Signature spoofing permission lost

### ISSUE THREAD

**Issue by kurt-by** [lineageos4microg/android_prebuilts_prebuiltapks#47]
March 24 update for a3exlte performed without errors. Only CoronaWarnApp cries: there is no exposure notification framework. Reason see screenshot
![Screenshot_20210325-024632_microG_Services_Core](https://user-images.githubusercontent.com/26526996/112406915-66980300-8d15-11eb-9fb4-06d91e16f0c3.png)

**Comment by spolack** [comment]
Seems i've found the issue. Was introduced by #44 

-> GmsCore/sysconfig-com.google.android.gms.xml
```
LOCAL_REQUIRED_MODULES := privapp-permissions-com.google.android.gms.xml
LOCAL_REQUIRED_MODULES := sysconfig-com.google.android.gms.xml
```

Once someone creates a fix PR i'll be happy to review and spin up a new build.
Furthermore i did withdraw the "broken" builds.


Actually they were not broken, but missing the included permissions, which could be granted manually.

**Comment by kurt-by** [comment]
Bug fix confirmed with march 26  build of a3xelte
