### ISSUE TITLE
Migration from official 18.1 breaks microG

### ISSUE THREAD

**Issue by kurt-by** [lineageos4microg/android_prebuilts_prebuiltapks#49]
Clean flash of April 1st L4M bacon shows no significant microG bugs.
Clean flash of official 18.1 April 1st and migrating to L4M works on lineage recovery without migration zip.
After migration microG self check shows all permission from approximate location to SMS are missing.
Tapping "Location modules" FCs microG service core app.

Edit: exactly same behaviour with jactivelte and twrp. Findings: migration is possible with or without migration zip. No difference in permission/fc issue. Installation can be repaired by wiping data partition in twrp.

**Comment by bananer** [comment]
Could you provide a logcat for the FC?

**Comment by kurt-by** [comment]
@bananer here you are
[microgfc.txt](https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/files/6304796/microgfc.txt)

**Comment by bananer** [comment]
Relevant line for the crash is probably `ActivityManager: Permission Denial: Accessing service org.microg.nlp.backend.ichnaea/.BackendService from pid=6442, uid=10151 requires android.permission.ACCESS_COARSE_LOCATION`

That seems like if you grant the premissions manually, it should stop crashing. Could that be a workaround for the migration cases?

**Comment by kurt-by** [comment]
I think a workaround for migration cases is Installation of a microG package like https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/download/2020.11.28/MinMicroG-NoGoolag-2.9-20201128144716.zip

Please contact me, if there are bug fixes to test.

**Comment by bananer** [comment]
Is this still relevant?

**Comment by kurt-by** [comment]
Just testet with jactivelte migration from oct 14 lineageos to oct 19 microG fork works. All selfcheck boxes checked.

**Comment by kurt-by** [comment]
Hast du gesehen ? Keine Builds seit Freitag 10 Uhe

28.10.2021 14:39:54 Philip Nagler-Frank ***@***.***>:
