### ISSUE TITLE
New microG & F-Droid versions

### ISSUE THREAD

**Issue by vanMacG** [lineageos4microg/android_prebuilts_prebuiltapks#51]
Hi,
just a quick reminder, there are new versions of microG and F-Droid available.

GmsCore v0.2.19.211515: https://microg.org/fdroid/repo/com.google.android.gms-211515038.apk
F-Droid Client 1.12.1 (1012051): https://f-droid.org/repo/org.fdroid.fdroid_1012051.apk

Thanks for updating!

**Comment by bananer** [comment]
Done, thanks!
