### ISSUE TITLE
microG update

### ISSUE THREAD

**Issue by ale5000-git** [lineageos4microg/android_prebuilts_prebuiltapks#53]
Please update microG Services Core to 0.2.21.212158

**Comment by javiims** [comment]
Can you update microG so as to it fixes the issue with Chromecast?

**Comment by bananer** [comment]
microG should update through F-Droid, so you don't need to wait for updated ROM builds.

**Comment by DPTJKKVH** [comment]
It actually doesn't, only if you manually installed it after flashing the ROM. At least that is my experience on three different devices.

Also if the ROM ships an older version of microG than installed on the system, it will actually downgrade microG, doesn't it?

So it is really desireable to build the ROMs with up to date microG versions included.

**Comment by ale5000-git** [comment]
@bananer: I know but if you add the account on the first run of the ROM where you can't update microG you can have issues.
In old versions of microG there are some issues that are now fixed (especially with settings).

**Comment by ghost** [comment]
> Also if the ROM ships an older version of microG than installed on the system, it will actually downgrade microG, doesn't it?

Two different apks:

One on `/system/priv-app/GmsCore/GmsCore.apk`, that is the base application on the system

One on `/data/app/com.google.android.gms-1/base.apk`, that is the updates you apply on top of the system apk (whether it be through F-Droid, or via manual install.)

The apk on `/data` takes priority, and a rom update only replaces the one on `/system`.

**Comment by bananer** [comment]
Updated yesterday
