### ISSUE TITLE
Update microG version

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/android_prebuilts_prebuiltapks#56]
LineageOS for microG 18.1 2021-08-11 for FP3 still contained the very old [v0.2.19.211515](https://github.com/microg/GmsCore/releases/tag/v0.2.19.211515)  of microG Core, which caused a bug (https://github.com/microg/GmsCore/issues/1544) in GCM registration for me.

It would be great if that was updated, so the setup works with less problems.
In my case upgrading to [v0.2.22.212658](https://github.com/microg/GmsCore/releases/tag/v0.2.22.212658) did fix the problem.

**Comment by bananer** [comment]
Updated in https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/commit/fb52fd3ec0a6c663e95dc74d025a2f182ac6c1db

New builds coming soon.
