### ISSUE TITLE
29.08.2018 cheeseburger nighly does not allow to switch wifi on

### ISSUE THREAD

**Issue by maxammann** [lineageos4microg/android_prebuilts_prebuiltapks#6]
Not sure if this is a bug of this build or lineage. I'll report it upstream if somebody else has the same problems.

The system ui just crashes if I try to enable wifi.

**Comment by atorralba** [comment]
Same here. Using latest TWRP, firmware and vendor images.

**Comment by maxammann** [comment]
No longer have this problem.
