### ISSUE TITLE
Are the previous LineageOS 16 device builds available anywhere?

### ISSUE THREAD

**Issue by mrspiderbrain** [lineageos4microg/android_prebuilts_prebuiltapks#60]
Hi, there doesn't seem to have been as resolution of the privacy guard feature downgrade for LineageOS17+, and so version 16 seems the most secure one available, from many people's perspective. Versions were available on 
https://download.lineage.microg.org/

but are no longer listed. Are they available anywhere, to your knowledge, and if not, would it be possible to create new builds using 
https://github.com/lineageos4microg/docker-lineage-cicd

**Comment by bananer** [comment]
No, disk space is limited so we did not keep them. You could still build it yourself.
