### ISSUE TITLE
To remove Yahoo and WUnderground providers

### ISSUE THREAD

**Issue by ghost** [lineageos4microg/android_prebuilts_prebuiltapks#7]
Seems both APIs will be closed. LOS will remove both weather providers when these commits are merged:
LOS 15.1:
https://review.lineageos.org/c/LineageOS/android/+/237893
LOS 16.0:
https://review.lineageos.org/c/LineageOS/android/+/227747

**Comment by corna** [comment]
Done in dfc5f9ccb84064f67ac15531c72b2625c569e103, thanks
